name: Manual Trigger Workflow with username
#get username information
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "Select the Environment"
        default: "Preprod"
        required: true
        type: string
        options:
          - "preprod"
          - "orange"

jobs:
  print-environment:
    runs-on: ubuntu-latest

    steps:
      - name: trigger the preprod environment
        run: echo The username is ${{ inputs.environment }}
